FROM python:3.12

ENV PYTHONBUFFERED=1

WORKDIR /django_docker

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD python manage.py runserver 0.0.0.0:8000

EXPOSE 8000